package:
    name:           php-merchant-okpay
    namespace:      hiqdev\php\merchant\okpay
    title:          OKPAY plugin for PHP merchant library
    type:           library
    keywords:       php, okpay, merchant
    description:    |
        [OKPAY](https://okpay.com/) plugin for [PHP merchant library](https://github.com/hiqdev/php-merchant).

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
